version: '3.8'

services:
  face_swap_mongo:
    image: mongo:latest
    container_name: face_swap_mongo
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: .
    container_name: face_swap_backend
    restart: always
    ports:
      - "7860:7860"
    depends_on:
      - face_swap_mongo
    volumes:
      - ./backend/models:/home/user/app/models
      - ./uploads:/home/user/app/uploads